### ISSUE TITLE
doubledown: Decider screen not showing timer modal when player screens do 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#260] opened 2017-05-04 17:15 UTC
All screens should have the timer modal when the players do. This is reflected in the mockups and the reason is it helps the decider know when to end another player's turn if they start to speak beyond the time they have allocated. 

right now, the decider screen stays on the dialog box. This is not the end of the world. Therefore, I am putting into icebox. 

![img_7298](https://cloud.githubusercontent.com/assets/10051544/25716030/9d01f46e-30cb-11e7-9a4f-b306cf21ed3f.JPG)

**Comment by esalling23** [comment] 2017-05-09 21:50
closed the duplicate of this issue, #206

**Comment by esalling23** [comment] 2017-05-09 21:54
<img width="224" alt="screen shot 2017-05-09 at 5 48 11 pm" src="https://cloud.githubusercontent.com/assets/11821504/25874326/02374006-34e0-11e7-8633-6a68a6b6bf7d.png"> <img width="213" alt="screen shot 2017-05-09 at 5 48 03 pm" src="https://cloud.githubusercontent.com/assets/11821504/25874329/0972ee88-34e0-11e7-9f84-2d193e99848e.png">

Currently the decider sees the speech bubble throughout the entire "screen" rather than seeing the timer. 

from #206 : 
" Right now the decider instructions/speech bubble, player options, and timer are all on one screen. Deciders should have 2 different sets of instructions for the speech bubble and for the timer. This means separating the timer into its own screen. "

**Closed** 2018-11-26 16:43 UTC
Labels: ADDITIONS, enhancement
