### ISSUE TITLE
UX: If a player reloads during a running timer, the timer pauses until they reconnect

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#165] opened 2017-04-14 16:45 UTC
This is a minor issue, but players effectively have a way to prolong the timer by refreshing their own devices. The timer will hang at its current value until the refreshing player is able to re-connect to the game.

**Comment by esalling23** [comment] 2017-04-14 22:05
@jpailthorpe This is pretty much working as intended - not sure what to do when players disconnect in the middle of a time other than pausing the timer until they reconnect.

**Comment by jpailthorpe** [comment] 2017-04-17 16:58
This is good to know @mattwbenson, but yes @esalling23 you are correct. This is the only way we can deal with this the most effectively. I'm going to close this.

**Closed by jpailthorpe** 2017-04-17 16:58 UTC
Labels: EXPERIENCE
