### ISSUE TITLE
UX/iOS: Hidden Agenda items getting forced out of layout, are made unreadable

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#174] opened 2017-04-18 14:55 UTC
![img_0155](https://cloud.githubusercontent.com/assets/12397944/25137328/731614ee-2425-11e7-8ee2-e8fd1ba025d1.PNG)

**Comment by esalling23** [comment] 2017-04-18 15:00
known issue

**Comment by esalling23** [comment] 2017-04-18 15:01
@mattwbenson duplicate of #95 please add anything to that issue

**Closed by esalling23** 2017-04-18 15:00 UTC
Labels: ENVIRONMENT(DEVICE), EXPERIENCE, iPodTouch-DEVICE
