### ISSUE TITLE
Leaderboard: Assets not loading, layout breaking on small mobile devices

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#161] opened 2017-04-14 15:21 UTC
![img_0149](https://cloud.githubusercontent.com/assets/12397944/25047408/7c393002-2104-11e7-9db1-5dc1e5dd2ba2.PNG)

This is on iPod Touch.

**Comment by johnnycrich** [comment] 2017-04-14 15:22
@mattwbenson If this happens again definitely want to know what the console says.

**Comment by esalling23** [comment] 2017-04-18 18:45
@jpailthorpe cannot reproduce this on production - can we move it to 'done'?

**Comment by jpailthorpe** [comment] 2017-04-19 20:37
yes, moving to done for now. We will start a fresh QA process for ipod size devices once we tackle new layout stuff. If its not fixed we will create a new issue

**Closed** 2017-05-04 23:05 UTC
Labels: ENVIRONMENT(DEVICE), EXPERIENCE, iPodTouch-DEVICE
