### ISSUE TITLE
Role Card: Padding on role card icon pushes bio role too far, title still not displaying properly. 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#95] opened 2017-04-07 15:06 UTC
Issue #82 is resolved,  the description text is returning to the bottom half of the card, which looks unintentional/awkward for UX.
![screen shot 2017-04-07 at 11 04 45 am](https://cloud.githubusercontent.com/assets/12397944/24806244/39bf3fa0-1b82-11e7-977b-2908aaed1020.png)

**Comment by jpailthorpe** [comment] 2017-04-07 15:36
It does looks like there is some unwanted padding near the top and the description. 

The agenda items, however, I will edit down to make to two lines, @esalling23 just fyi since its it displaying correctly.

**Comment by esalling23** [comment] 2017-04-07 18:44
@mattwbenson I cannot reproduce this, even when making the page full-screen. I see this: 
<img width="424" alt="screen shot 2017-04-07 at 2 42 39 pm" src="https://cloud.githubusercontent.com/assets/11821504/24814656/8a5b7fe6-1ba0-11e7-841d-6e1d24b3cc4e.png">
Please confirm screen size and if there is any missing content.

**Comment by mattwbenson** [comment] 2017-04-07 18:49
I didn't see any missing content, but my windows were all narrow and tall,
only wide enough to see the standard game screen.

**Comment by esalling23** [comment] 2017-04-07 18:54
@mattwbenson Thanks, in the future we should be including screen size either in pixels or by defining the device type (iphone5, ipad, etc) for every issue or update when it is made, especially for layout issues. 
@jpailthorpe For now we will be capping height to avoid percentage-based background problems.

**Comment by jpailthorpe** [comment] 2017-04-11 22:54
We are going to wait on this until we have time to get Erica's desktop height cap in.

**Comment by esalling23** [comment] 2017-04-18 18:27
This has been fixed on iOS iPhone 6 and up

**Closed** 2017-04-19 21:30 UTC
Labels: EXPERIENCE
