### ISSUE TITLE
UX (minor): Players can be assigned identical player icons by leaving, rejoining lobby

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#163] opened 2017-04-14 15:57 UTC
I was able to do this on the iPad 4 after having it join a lobby as the second player. Once I had added three other players to the game, I had the iPad leave the game, and then rejoin:

![img_0091](https://cloud.githubusercontent.com/assets/12397944/25048265/7b644edc-2109-11e7-98b7-686ca4b68a8e.PNG)

**Comment by jpailthorpe** [comment] 2017-05-11 19:54
duplicate of #317

**Closed by jpailthorpe** 2017-05-11 19:54 UTC
Labels: EXPERIENCE, IMPROVEMENTS
