### ISSUE TITLE
Players are getting disconnected on mobile - still appears to be in game but reload kicks them out 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#185] opened 2017-04-18 17:24 UTC
- Player phone goes to sleep 
- Other players get disconnected message (waiting ~12s)
- Player who was disconnected reopens phone - still appears to be in the game, no modal, everythings fine 
- Player who was disconnected reloads page to try to "reconnect" 
- Player is then completely disconnected (sent to lobby login screen) 
- Other players still see disconnected message (waiting ~5s)

**Comment by jpailthorpe** [comment] 2017-04-18 18:22
@esalling23 any chance you were in lower power mode when the phone went to sleep? They shouldn't be going to sleep unless they are in low power mode or similar power saving feature. 

I'm also curious if the timer actually elapsed into disconnection making the game actually over, but the modal on the screen simply didn't tell the players what was going on.

**Comment by esalling23** [comment] 2017-04-18 18:30
@jpailthorpe Bin had his phone in normal, not "low power" mode when playing
I also am pretty sure the timer never hit 0 before it reloaded like normal, it was counting down the entire time

**Comment by jpailthorpe** [comment] 2017-04-18 21:24
Were you playing on chrome @esalling23

**Comment by jpailthorpe** [comment] 2017-04-18 21:28
I was unable to reproduce the results you have for when the phone goes to sleep. When it happened to me, the phone was disconnected, and all other devices got kicked back to the lobby like its is supposed to. The phone that went to sleep had the yikes error message, and upon refresh also went back to the lobby. 

I think this might have been affected by the debrief updates that were broken all day. Either way, lets keep an eye on it if it comes up again. Will be moving to done for now.

**Comment by jpailthorpe** [comment] 2017-04-18 21:28
OH also...

it looks like safari is not going to sleep on ios devices, but chrome is.

**Closed** 2017-04-19 16:10 UTC
Labels: bug
