### ISSUE TITLE
Dialogbox: next button arrow scrunches into the word "next" (ipad only)

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#147] opened 2017-04-12 20:47 UTC
![img_3279](https://cloud.githubusercontent.com/assets/10051544/24978746/c221dd3c-1f9f-11e7-9487-d5bcbe5a17b9.PNG)
screen from iphone6splus. 

My suggestion is to remove the arrow completely. I think this will solve alot of these issues, and I'm not sure it adds much anyway.

**Comment by esalling23** [comment] 2017-04-18 18:43
confirmed fixed on production

**Comment by mattwbenson** [comment] 2017-04-19 18:33
Still seeing this on iPad 4:

![img_0092](https://cloud.githubusercontent.com/assets/12397944/25195958/266efb40-250d-11e7-9ca2-128f5465af58.PNG)

**Comment by esalling23** [comment] 2017-04-20 19:16
This is only appearing on mobile devices but not at the same screen size on desktop, so media queries have not been able to target just mobile devices at this size. We will need to either look into ways of targeting mobile devices with media queries other than by simply screen size, or add a class to all elements that display differently on mobile but not on desktop, and target them that way. 

Moving on for now since @jpailthorpe has specified this is low priority.

**Comment by jpailthorpe** [comment] 2017-04-28 16:27
this might help! 

https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by jpailthorpe** [comment] 2017-05-08 16:18
we removed the arrow in order to avoid this reoccurring issue.

**Closed** 2017-05-08 18:26 UTC
Labels: iPad4-DEVICE
