### ISSUE TITLE
DC Timer failing to send players back to login/end game on server disconnect 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#175] opened 2017-04-18 15:09 UTC
I had this happen during the start of the game in the Meet phase. I stopped in the middle of things to take a screencap on the iPod Touch for another issue, and the iPod got disconnected from the server while safari was minimized (while I was uploading the screencap). This was the game state when I returned to safari:

![img_0156](https://cloud.githubusercontent.com/assets/12397944/25137869/fc7f6cc0-2426-11e7-98a1-7e30cf99f366.PNG)

After it got disconnected, the DC timer appeared on the other devices (an iPad 4, the MotoG, and Chrome Desktop) and started to count down from 60. Desktop and the MotoG both counted down and then returned to the login screen, but the iPad hung at 0s indefinitely:
![img_0009](https://cloud.githubusercontent.com/assets/12397944/25138024/69e0a072-2427-11e7-9459-e2f1e9d88fd2.PNG)

**Comment by jpailthorpe** [comment] 2017-04-19 20:36
Going to try and reproduce and see if this is still happening specifically on ipad after updates from yesterday

**Comment by johnnycrich** [comment] 2017-05-03 17:52
Assigning to @mattwbenson to try to repro since this may be fixed along with other fixes.

**Comment by jpailthorpe** [comment] 2017-05-03 17:55
Saw this intermittently yesterday, but couldn't lock down why or when consistently besides knowing it was happening during the second reconnect (when we got the safari web exception referenced in another issue). But agree we should keep moving.

**Closed** 2017-05-03 18:03 UTC
Labels: bug, ENVIRONMENT(DEVICE), iPad4-DEVICE, iPodTouch-DEVICE
