### ISSUE TITLE
Reconnection: Refreshing will attempt to reconnect even if game is over

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#30] opened 2017-03-23 21:35 UTC
You have to close the tab and reopen in a new tab in order to play again

**Comment by jpailthorpe** [comment] 2017-03-27 16:50
related to #41

**Comment by mattwbenson** [comment] 2017-03-31 16:24
Still seeing this behavior as of 3/31

**Comment by mattwbenson** [comment] 2017-04-04 14:56
Still seeing this issue whenever I finish a game.

**Comment by johnnycrich** [comment] 2017-04-04 15:41
@mattwbenson Currently it's basically impossible to finish a game due to there being no scoreboard screen yet. What does "finishing a game" look like for you?

**Comment by mattwbenson** [comment] 2017-04-04 15:44
Oh, sorry, basically, whenever the decider has finished choosing a winner and identifying whether or not the proposal qualified for bonus points. Basically, when I reached the end point of the game where it stopped giving me new instructions/buttons.

**Comment by jpailthorpe** [comment] 2017-04-11 22:21
Matt, this should be fixed but please verify

**Comment by jpailthorpe** [comment] 2017-04-12 23:30
If the game is over ie. decider has quit back to main menu, the count out timer has expired, or the decider/host has closed the window, the game does kick everyone back to the login page as designed. However, there are other issues somewhat related to situations where the decider has refreshed but is sent back to the login screen. The game doesn't recognize the game has "ended" and then when a player refreshes, they just reload the current template, creating a situation that seems like this issue, but is different enough to separate them.  

I have verified that when you close the window, open a new tab, etc. you won't try to reconnect back to the same "Dead" game. Therefore, moving this one to done.

**Closed** 2017-04-19 16:10 UTC
Labels: bug, PROBLEMS
